### ISSUE TITLE
Unable to run this dockerfile in AWS-Linux

### ISSUE THREAD

**Issue by rakeshnambiar** [andreptb/Dockerfiles#19]
Please advise me on the below error.

Step 3/5 : RUN curl -fsSL http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share   && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
 ---> Running in 8098660b8c44
/bin/sh: curl: not found
tar: invalid magic
tar: short read
The command '/bin/sh -c curl -fsSL http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share   && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn' returned a non-zero code: 1

**Comment by rflbianco** [comment]
Hi @rakeshnambiar , you're probably using one of the **non-alpine** images of Maven (`maven:$VERSION-jdk8/7/6`). I have reviewed them, and these ones are broken. For now, use the **alpine-based** ones ( eg. `maven:$VERSION-jdk8/7/6-alpine`) instead.

It happened that we moved our images to be Alpine-based by default (not as just a variant). Some of them, like the Maven ones, haven't been reworked, as in production we still use the ones with the `-alpine` suffix.

In this particular case, the `maven:$VERSION-jdk8/7/6` inherit from `oracle-java:jdk8/7/6`. This one, used to be Ubuntu-based, but now is Alpine-based. Therefore, it used to have the `curl` installed, but it doesn't have anymore.

**Comment by rakeshnambiar** [comment]
Hi @rflbianco .. Thanks for your reply. However, to incorporate your suggestion, I may need more support because I am pretty new to this. I have tried the below and it didn't work. Could you please check?

Option1: FROM maven-jdk8-alpine

Option2: FROM andreptb/oracle-java:8-alpine

**Comment by rflbianco** [comment]
@rakeshnambiar , I've just corrected my comment with the right image name:version. Consider, for the example `$VERSION = 3.3.9`.

**Comment by rakeshnambiar** [comment]
Hi @rflbianco .. I am sorry, below Docker file not working for me.
--------------------------------------------------------------------------------------
FROM maven-jdk8-alpine

ENV MAVEN_VERSION 3.3.9

RUN curl -fsSL http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

CMD ["mvn"]

**Comment by lucianomagrao** [comment]
Just use this one
https://github.com/andreptb/Dockerfiles/blob/master/maven/alpine/jdk-8/Dockerfile
or pull it from hub `andreptb/maven:3.3.9-alpine`

2017-08-30 11:14 GMT-03:00 rakeshnambiar <notifications@github.com>:

**Comment by rakeshnambiar** [comment]
I have copy pasted the contents of the link which you mentioned and end up with the same error.

repository maven-jdk8-alpine not found: does not exist or no pull access

**Comment by rakeshnambiar** [comment]
@rflbianco ... It's worked finally.

**Comment by lucianomagrao** [comment]
Are you sure? That's no mention of maven-jdk8-alpine in the file that I linked

**Comment by rakeshnambiar** [comment]
There was some issue while replacing the new content. It's worked finally. Thank a lot.

**Comment by rakeshnambiar** [comment]
Hi @leslau .. It will be great, if you could help me to add git installation also in the same Dockerfile.

I have tried 'RUN yum -y install git' and it didn't work.


/bin/sh: yum: not found
The command '/bin/sh -c yum -y update' returned a non-zero code: 127

**Comment by rflbianco** [comment]
@rakeshnambiar, this `Dockerfile` shouldn't work. The `FROM` clause should be something like `FROM andreptb/maven:3.3.9-jdk8-alpine`

Also, your `RUN curl ... ` isn't necessary, as this image does exactly that on top of `andreptb/oracle-java:8-alpine`, as you can see in the Maven's [`Dockerfile`](https://github.com/andreptb/Dockerfiles/blob/master/maven/alpine/jdk-8/Dockerfile).

So, if your looking to just use Maven in Docker, I suggest you to just run it as described in the Maven's image [README.md](https://github.com/andreptb/Dockerfiles/blob/master/maven/README.md).

If your looking to build your own image of Maven, you our [`Dockerfile`](https://github.com/andreptb/Dockerfiles/blob/master/maven/alpine/jdk-8/Dockerfile) as example.

Finally, if you want to build your image on top of our Maven image, then the following code should give you a start:

```
FROM andreptb/maven:3.3.9-jdk8-alpine

RUN <your custom code >
```
Remember that this image is Alpine-based, so a lot of programs are not available. If you look at our own Dockerfile, you see that we add and remove tools like `wget` in the `RUN` clause. That is for lightening the resulting image.

**Comment by rflbianco** [comment]
@rakeshnambiar , Alpine has its own package manager, `apk`. So `yum` is not going to work.
