### ISSUE TITLE
Unable to run clean command because plugin was not found.

### ISSUE THREAD

**Issue by rhuanpacto** [andreptb/Dockerfiles#26]
I ran the command
`docker run -it --rm --name my-project -v "$PWD":/data andreptb/maven:3.2.5-jdk6 mvn clean`

```
Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies 
could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:
maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:
maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2):
Received fatal alert: protocol_version -> [Help 1]
```

What's the problem?

**Comment by andreptb** [comment]
@rhuanpacto ,

I couldn't reproduce this problem. Can you try the same command with [library/maven](https://hub.docker.com/_/maven/) image? 

Maybe i'ts a problem in your docker environment.

**Comment by andrealbinop** [comment]
@rhuanpacto ,

I was able to reproduce the problem now. It seems the current SSL version used in maven central repo (TLS 1.2) is not supported by jdk 1.6, hence the failure fetching any dependencies from there.

You don't need to use maven with jdk 1.6 to build your projects. You can use a newer jdk/maven but configure to be compatible with source code for java 6. Check [maven-compiler-plugin documentation](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html).

I'm affraid there's nothing more we can do regarding this issue.
