### ISSUE TITLE
Correct your docker URLs

### ISSUE THREAD

**Issue by rhuanpacto** [andreptb/Dockerfiles#28]
Please man, correct your Docker URLs. I've tried to use one of your docker images but the address was wrong.

So instead of `docker run -it --rm -d -p 8888:8080 tomcat:6.0.53-jdk6` I needed to use `docker run -it --rm -d -p 8888:8080 andreptb/tomcat:6.0.53-jdk6`. Don't forget that the tag `tomcat` is already binded to the official tomcat docker hub (https://hub.docker.com/_/tomcat/)

Ty.

**Comment by andrealbinop** [comment]
Thanks!
