### ISSUE TITLE
Have andreptb/oracle-java been removed from DockerHub?

### ISSUE THREAD

**Issue by Asgavar** [andreptb/Dockerfiles#34]
As the title says, this image seems to be missing. Was it on purpose?

https://hub.docker.com/r/andreptb/oracle-java/

**Comment by andrealbinomeli** [comment]
Unfortunately yes, dockerhub removed stating licensing problems

**Comment by lucianomagrao** [comment]
Docker hub removed all Oracle Java based images. I think that's because Oracle just create his own docker repository
